/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CartSetCustomPriceOnItemsRequest,
  RpcStatus,
} from '../models/index';
import {
    CartSetCustomPriceOnItemsRequestFromJSON,
    CartSetCustomPriceOnItemsRequestToJSON,
    RpcStatusFromJSON,
    RpcStatusToJSON,
} from '../models/index';

export interface CartSetCustomPriceOnItemsOperationRequest {
    body: CartSetCustomPriceOnItemsRequest;
}

/**
 * 
 */
export class CartApi extends runtime.BaseAPI {

    /**
     */
    async cartSetCustomPriceOnItemsRaw(requestParameters: CartSetCustomPriceOnItemsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling cartSetCustomPriceOnItems.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Authorization authentication
        }

        const response = await this.request({
            path: `/cart.Cart/SetCustomPriceOnItems`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CartSetCustomPriceOnItemsRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async cartSetCustomPriceOnItems(requestParameters: CartSetCustomPriceOnItemsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.cartSetCustomPriceOnItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
