/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CartProductConfigurationStepOption
 */
export interface CartProductConfigurationStepOption {
    /**
     * 
     * @type {string}
     * @memberof CartProductConfigurationStepOption
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartProductConfigurationStepOption
     */
    'grn'?: string;
    /**
     * 
     * @type {CartLocalizedText}
     * @memberof CartProductConfigurationStepOption
     */
    'label'?: CartLocalizedText;
    /**
     * 
     * @type {CartMoney}
     * @memberof CartProductConfigurationStepOption
     */
    'priceVariation'?: CartMoney;
    /**
     * 
     * @type {number}
     * @memberof CartProductConfigurationStepOption
     */
    'weightVariation'?: number;
    /**
     * 
     * @type {OptionImage}
     * @memberof CartProductConfigurationStepOption
     */
    'image'?: OptionImage;
    /**
     * 
     * @type {boolean}
     * @memberof CartProductConfigurationStepOption
     */
    'hasQuantity'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CartProductConfigurationStepOption
     */
    'quantity'?: number;
}
