/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CartShipmentData
 */
export interface CartShipmentData {
    /**
     * 
     * @type {string}
     * @memberof CartShipmentData
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartShipmentData
     */
    'method'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartShipmentData
     */
    'shipmentGrn'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartShipmentData
     */
    'payload'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CartShipmentData
     */
    'cartItemIds'?: Array<string>;
    /**
     * 
     * @type {CartMoney}
     * @memberof CartShipmentData
     */
    'fee'?: CartMoney;
    /**
     * 
     * @type {string}
     * @memberof CartShipmentData
     */
    'label'?: string;
    /**
     * 
     * @type {CartMoney}
     * @memberof CartShipmentData
     */
    'vatAmount'?: CartMoney;
    /**
     * 
     * @type {number}
     * @memberof CartShipmentData
     */
    'vatPercentage'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CartShipmentData
     */
    'vatInaccurate'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CartShipmentData
     */
    'vatCalculated'?: boolean;
}
