/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CartSortOrder = {
    Desc: 'DESC',
    Asc: 'ASC'
} as const;
export type CartSortOrder = typeof CartSortOrder[keyof typeof CartSortOrder];


export function CartSortOrderFromJSON(json: any): CartSortOrder {
    return CartSortOrderFromJSONTyped(json, false);
}

export function CartSortOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartSortOrder {
    return json as CartSortOrder;
}

export function CartSortOrderToJSON(value?: CartSortOrder | null): any {
    return value as any;
}

