/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CartListCartsResponse
 */
export interface CartListCartsResponse {
    /**
     * 
     * @type {Array<CartCartData>}
     * @memberof CartListCartsResponse
     */
    'carts'?: Array<CartCartData>;
    /**
     * 
     * @type {string}
     * @memberof CartListCartsResponse
     */
    'nextPageToken'?: string;
}
