/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CartCartStatus = {
    Unknown: 'UNKNOWN',
    Active: 'ACTIVE',
    Inactive: 'INACTIVE'
} as const;
export type CartCartStatus = typeof CartCartStatus[keyof typeof CartCartStatus];


export function CartCartStatusFromJSON(json: any): CartCartStatus {
    return CartCartStatusFromJSONTyped(json, false);
}

export function CartCartStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartCartStatus {
    return json as CartCartStatus;
}

export function CartCartStatusToJSON(value?: CartCartStatus | null): any {
    return value as any;
}

