/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CartGetActiveCartByCustomerRequest
 */
export interface CartGetActiveCartByCustomerRequest {
    /**
     * 
     * @type {string}
     * @memberof CartGetActiveCartByCustomerRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartGetActiveCartByCustomerRequest
     */
    'customerGrn'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartGetActiveCartByCustomerRequest
     */
    'channel'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartGetActiveCartByCustomerRequest
     */
    'market'?: string;
    /**
     * 
     * @type {CartCurrency}
     * @memberof CartGetActiveCartByCustomerRequest
     */
    'currency'?: CartCurrency;
}
