/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CartPaymentData
 */
export interface CartPaymentData {
    /**
     * 
     * @type {string}
     * @memberof CartPaymentData
     */
    'code'?: string;
    /**
     * 
     * @type {CartLocalizedText}
     * @memberof CartPaymentData
     */
    'title'?: CartLocalizedText;
    /**
     * 
     * @type {string}
     * @memberof CartPaymentData
     */
    'payload'?: string;
    /**
     * 
     * @type {CartMoney}
     * @memberof CartPaymentData
     */
    'fee'?: CartMoney;
    /**
     * 
     * @type {CartMoney}
     * @memberof CartPaymentData
     */
    'amount'?: CartMoney;
    /**
     * 
     * @type {CartLocalizedText}
     * @memberof CartPaymentData
     */
    'label'?: CartLocalizedText;
    /**
     * 
     * @type {CartLocalizedText}
     * @memberof CartPaymentData
     */
    'description'?: CartLocalizedText;
    /**
     * 
     * @type {CartMoney}
     * @memberof CartPaymentData
     */
    'vatAmount'?: CartMoney;
    /**
     * 
     * @type {number}
     * @memberof CartPaymentData
     */
    'vatPercentage'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CartPaymentData
     */
    'vatInaccurate'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CartPaymentData
     */
    'vatCalculated'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CartPaymentData
     */
    'isUpfront'?: boolean;
}
