/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CartCartData
 */
export interface CartCartData {
    /**
     * 
     * @type {string}
     * @memberof CartCartData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartCartData
     */
    'grn'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartCartData
     */
    'channel'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartCartData
     */
    'market'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartCartData
     */
    'locale'?: string;
    /**
     * 
     * @type {Array<CartCartItem>}
     * @memberof CartCartData
     */
    'items'?: Array<CartCartItem>;
    /**
     * 
     * @type {Array<CartPaymentData>}
     * @memberof CartCartData
     */
    'payments'?: Array<CartPaymentData>;
    /**
     * 
     * @type {Array<CartShipmentData>}
     * @memberof CartCartData
     */
    'shipments'?: Array<CartShipmentData>;
    /**
     * 
     * @type {Array<CartPromotionData>}
     * @memberof CartCartData
     */
    'promotions'?: Array<CartPromotionData>;
    /**
     * 
     * @type {CartCurrency}
     * @memberof CartCartData
     */
    'currency'?: CartCurrency;
    /**
     * 
     * @type {Array<CartCartSubtotal>}
     * @memberof CartCartData
     */
    'subtotals'?: Array<CartCartSubtotal>;
    /**
     * 
     * @type {CartMoney}
     * @memberof CartCartData
     */
    'total'?: CartMoney;
    /**
     * 
     * @type {CartMoney}
     * @memberof CartCartData
     */
    'totalDue'?: CartMoney;
    /**
     * 
     * @type {boolean}
     * @memberof CartCartData
     */
    'vatIncluded'?: boolean;
    /**
     * 
     * @type {CartPostalAddress}
     * @memberof CartCartData
     */
    'billingAddress'?: CartPostalAddress;
    /**
     * 
     * @type {CartPostalAddress}
     * @memberof CartCartData
     */
    'shippingAddress'?: CartPostalAddress;
    /**
     * 
     * @type {CartCartStatus}
     * @memberof CartCartData
     */
    'status'?: CartCartStatus;
    /**
     * 
     * @type {CartCustomerData}
     * @memberof CartCartData
     */
    'customer'?: CartCustomerData;
    /**
     * 
     * @type {string}
     * @memberof CartCartData
     */
    'notes'?: string;
    /**
     * 
     * @type {Date}
     * @memberof CartCartData
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CartCartData
     */
    'updatedAt'?: Date;
}
