/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CartListCartsRequest
 */
export interface CartListCartsRequest {
    /**
     * 
     * @type {string}
     * @memberof CartListCartsRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {number}
     * @memberof CartListCartsRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof CartListCartsRequest
     */
    'pageToken'?: string;
    /**
     * 
     * @type {Array<ListCartsRequestSort>}
     * @memberof CartListCartsRequest
     */
    'sorts'?: Array<ListCartsRequestSort>;
    /**
     * 
     * @type {string}
     * @memberof CartListCartsRequest
     */
    'filterMask'?: string;
    /**
     * 
     * @type {ListCartsRequestFilter}
     * @memberof CartListCartsRequest
     */
    'filter'?: ListCartsRequestFilter;
}
