/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CartSetCustomPriceOnItemsRequestCartItem
 */
export interface CartSetCustomPriceOnItemsRequestCartItem {
    /**
     * 
     * @type {string}
     * @memberof CartSetCustomPriceOnItemsRequestCartItem
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CartSetCustomPriceOnItemsRequestCartItem
     */
    'freeOfCharge'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CartSetCustomPriceOnItemsRequestCartItem
     */
    'unset'?: boolean;
    /**
     * 
     * @type {CartMoney}
     * @memberof CartSetCustomPriceOnItemsRequestCartItem
     */
    'customPriceRow'?: CartMoney;
    /**
     * 
     * @type {CartMoney}
     * @memberof CartSetCustomPriceOnItemsRequestCartItem
     */
    'customPriceUnit'?: CartMoney;
    /**
     * 
     * @type {number}
     * @memberof CartSetCustomPriceOnItemsRequestCartItem
     */
    'discountPercentage'?: number;
}
