/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Get cart request
 * @export
 * @interface CartGetCartRequest
 */
export interface CartGetCartRequest {
    /**
     * The unique identifier for the tenant associated with the shopping cart.
     * @type {string}
     * @memberof CartGetCartRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartGetCartRequest
     */
    'cartId'?: string;
}
