/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CartSetAdditionalInfoRequest
 */
export interface CartSetAdditionalInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof CartSetAdditionalInfoRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartSetAdditionalInfoRequest
     */
    'cartId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartSetAdditionalInfoRequest
     */
    'productId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartSetAdditionalInfoRequest
     */
    'additionalInfo'?: string;
}
