/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CartCustomerData
 */
export interface CartCustomerData {
    /**
     * 
     * @type {string}
     * @memberof CartCustomerData
     */
    'customerGrn'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartCustomerData
     */
    'firstname'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartCustomerData
     */
    'lastname'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartCustomerData
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartCustomerData
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CartCustomerData
     */
    'groups'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CartCustomerData
     */
    'taxCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartCustomerData
     */
    'certifiedEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartCustomerData
     */
    'sdiCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartCustomerData
     */
    'fiscalCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartCustomerData
     */
    'companyName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CartCustomerData
     */
    'agentGrn'?: string;
}
