/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ListCartsRequestFilterCartStatus = {
    Unknown: 'UNKNOWN',
    Enabled: 'ENABLED',
    Disabled: 'DISABLED'
} as const;
export type ListCartsRequestFilterCartStatus = typeof ListCartsRequestFilterCartStatus[keyof typeof ListCartsRequestFilterCartStatus];


export function ListCartsRequestFilterCartStatusFromJSON(json: any): ListCartsRequestFilterCartStatus {
    return ListCartsRequestFilterCartStatusFromJSONTyped(json, false);
}

export function ListCartsRequestFilterCartStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCartsRequestFilterCartStatus {
    return json as ListCartsRequestFilterCartStatus;
}

export function ListCartsRequestFilterCartStatusToJSON(value?: ListCartsRequestFilterCartStatus | null): any {
    return value as any;
}

