/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ListCartsRequestFilter
 */
export interface ListCartsRequestFilter {
    /**
     * 
     * @type {Array<string>}
     * @memberof ListCartsRequestFilter
     */
    'searchTerms'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListCartsRequestFilter
     */
    'customerEmails'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListCartsRequestFilter
     */
    'customerFirstnames'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListCartsRequestFilter
     */
    'customerLastnames'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListCartsRequestFilter
     */
    'customerPhones'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListCartsRequestFilter
     */
    'cartIds'?: Array<string>;
    /**
     * 
     * @type {ListCartsRequestFilterCartStatus}
     * @memberof ListCartsRequestFilter
     */
    'cartStatus'?: ListCartsRequestFilterCartStatus;
    /**
     * 
     * @type {Array<ListCartsRequestFilterDate>}
     * @memberof ListCartsRequestFilter
     */
    'createdAt'?: Array<ListCartsRequestFilterDate>;
    /**
     * 
     * @type {string}
     * @memberof ListCartsRequestFilter
     */
    'agentGrn'?: string;
}
