/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ListCartsRequestFilterDate
 */
export interface ListCartsRequestFilterDate {
    /**
     * 
     * @type {Date}
     * @memberof ListCartsRequestFilterDate
     */
    'from'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListCartsRequestFilterDate
     */
    'to'?: Date;
}
