/* tslint:disable */
/* eslint-disable */
/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ListCartsRequestSort
 */
export interface ListCartsRequestSort {
    /**
     * evaluation_order is the order in which the sort will be applied. The lower the number, the earlier the sort will be applied.
     * @type {number}
     * @memberof ListCartsRequestSort
     */
    'evaluationOrder'?: number;
    /**
     * 
     * @type {SortSortField}
     * @memberof ListCartsRequestSort
     */
    'field'?: SortSortField;
    /**
     * 
     * @type {CartSortOrder}
     * @memberof ListCartsRequestSort
     */
    'order'?: CartSortOrder;
}
