/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartMoney } from '../models/CartMoney';
import { HttpFile } from '../http/http';

export class CartSetCustomPriceOnItemsRequestCartItem {
    'id'?: string;
    'freeOfCharge'?: boolean;
    'unset'?: boolean;
    'customPriceRow'?: CartMoney;
    'customPriceUnit'?: CartMoney;
    'discountPercentage'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "freeOfCharge",
            "baseName": "freeOfCharge",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "unset",
            "baseName": "unset",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "customPriceRow",
            "baseName": "customPriceRow",
            "type": "CartMoney",
            "format": ""
        },
        {
            "name": "customPriceUnit",
            "baseName": "customPriceUnit",
            "type": "CartMoney",
            "format": ""
        },
        {
            "name": "discountPercentage",
            "baseName": "discountPercentage",
            "type": "number",
            "format": "float"
        }    ];

    static getAttributeTypeMap() {
        return CartSetCustomPriceOnItemsRequestCartItem.attributeTypeMap;
    }

    public constructor() {
    }
}

