/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartAddProductsResponseItem } from '../models/CartAddProductsResponseItem';
import { HttpFile } from '../http/http';

export class CartAddProductsResponse {
    'items'?: Array<CartAddProductsResponseItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<CartAddProductsResponseItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CartAddProductsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

