/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListCartsRequestFilter } from '../models/ListCartsRequestFilter';
import { ListCartsRequestSort } from '../models/ListCartsRequestSort';
import { HttpFile } from '../http/http';

export class CartListCartsRequest {
    'tenantId'?: string;
    'pageSize'?: number;
    'pageToken'?: string;
    'sorts'?: Array<ListCartsRequestSort>;
    'filterMask'?: string;
    'filter'?: ListCartsRequestFilter;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "pageToken",
            "baseName": "pageToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "sorts",
            "baseName": "sorts",
            "type": "Array<ListCartsRequestSort>",
            "format": ""
        },
        {
            "name": "filterMask",
            "baseName": "filterMask",
            "type": "string",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "ListCartsRequestFilter",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CartListCartsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

