/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartCartItem } from '../models/CartCartItem';
import { CartCartStatus } from '../models/CartCartStatus';
import { CartCartSubtotal } from '../models/CartCartSubtotal';
import { CartCurrency } from '../models/CartCurrency';
import { CartCustomerData } from '../models/CartCustomerData';
import { CartMoney } from '../models/CartMoney';
import { CartPaymentData } from '../models/CartPaymentData';
import { CartPostalAddress } from '../models/CartPostalAddress';
import { CartPromotionData } from '../models/CartPromotionData';
import { CartShipmentData } from '../models/CartShipmentData';
import { HttpFile } from '../http/http';

export class CartCartData {
    'id'?: string;
    'grn'?: string;
    'channel'?: string;
    'market'?: string;
    'locale'?: string;
    'items'?: Array<CartCartItem>;
    'payments'?: Array<CartPaymentData>;
    'shipments'?: Array<CartShipmentData>;
    'promotions'?: Array<CartPromotionData>;
    'currency'?: CartCurrency;
    'subtotals'?: Array<CartCartSubtotal>;
    'total'?: CartMoney;
    'totalDue'?: CartMoney;
    'vatIncluded'?: boolean;
    'billingAddress'?: CartPostalAddress;
    'shippingAddress'?: CartPostalAddress;
    'status'?: CartCartStatus;
    'customer'?: CartCustomerData;
    'notes'?: string;
    'createdAt'?: Date;
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "grn",
            "baseName": "grn",
            "type": "string",
            "format": ""
        },
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string",
            "format": ""
        },
        {
            "name": "market",
            "baseName": "market",
            "type": "string",
            "format": ""
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<CartCartItem>",
            "format": ""
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "Array<CartPaymentData>",
            "format": ""
        },
        {
            "name": "shipments",
            "baseName": "shipments",
            "type": "Array<CartShipmentData>",
            "format": ""
        },
        {
            "name": "promotions",
            "baseName": "promotions",
            "type": "Array<CartPromotionData>",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "CartCurrency",
            "format": ""
        },
        {
            "name": "subtotals",
            "baseName": "subtotals",
            "type": "Array<CartCartSubtotal>",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "CartMoney",
            "format": ""
        },
        {
            "name": "totalDue",
            "baseName": "totalDue",
            "type": "CartMoney",
            "format": ""
        },
        {
            "name": "vatIncluded",
            "baseName": "vatIncluded",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "billingAddress",
            "baseName": "billingAddress",
            "type": "CartPostalAddress",
            "format": ""
        },
        {
            "name": "shippingAddress",
            "baseName": "shippingAddress",
            "type": "CartPostalAddress",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CartCartStatus",
            "format": ""
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "CartCustomerData",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return CartCartData.attributeTypeMap;
    }

    public constructor() {
    }
}



