/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CartCustomerData {
    'customerGrn'?: string;
    'firstname'?: string;
    'lastname'?: string;
    'email'?: string;
    'phoneNumber'?: string;
    'groups'?: Array<string>;
    'taxCode'?: string;
    'certifiedEmail'?: string;
    'sdiCode'?: string;
    'fiscalCode'?: string;
    'companyName'?: string;
    'agentGrn'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customerGrn",
            "baseName": "customerGrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstname",
            "baseName": "firstname",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastname",
            "baseName": "lastname",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "taxCode",
            "baseName": "taxCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "certifiedEmail",
            "baseName": "certifiedEmail",
            "type": "string",
            "format": ""
        },
        {
            "name": "sdiCode",
            "baseName": "sdiCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "fiscalCode",
            "baseName": "fiscalCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "companyName",
            "baseName": "companyName",
            "type": "string",
            "format": ""
        },
        {
            "name": "agentGrn",
            "baseName": "agentGrn",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CartCustomerData.attributeTypeMap;
    }

    public constructor() {
    }
}

