/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartItemCustomPrice } from '../models/CartItemCustomPrice';
import { CartMoney } from '../models/CartMoney';
import { CartProductConfigurationStep } from '../models/CartProductConfigurationStep';
import { HttpFile } from '../http/http';

export class CartCartItem {
    'id'?: string;
    'productGrn'?: string;
    'productConfiguration'?: Array<CartProductConfigurationStep>;
    'quantity'?: number;
    'price'?: CartMoney;
    'listPrice'?: CartMoney;
    'discount'?: CartMoney;
    'basePrice'?: CartMoney;
    'customPrice'?: CartItemCustomPrice;
    'vatAmount'?: CartMoney;
    'vatPercentage'?: number;
    'vatInaccurate'?: boolean;
    'vatCalculated'?: boolean;
    'localizedName'?: { [key: string]: string; };
    'productCode'?: string;
    'productSku'?: string;
    'imageGrn'?: string;
    'variantOptions'?: string;
    'isVirtual'?: boolean;
    'promotionGrns'?: Array<string>;
    'additionalInfo'?: string;
    'productData'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "productGrn",
            "baseName": "productGrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "productConfiguration",
            "baseName": "productConfiguration",
            "type": "Array<CartProductConfigurationStep>",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "CartMoney",
            "format": ""
        },
        {
            "name": "listPrice",
            "baseName": "listPrice",
            "type": "CartMoney",
            "format": ""
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "CartMoney",
            "format": ""
        },
        {
            "name": "basePrice",
            "baseName": "basePrice",
            "type": "CartMoney",
            "format": ""
        },
        {
            "name": "customPrice",
            "baseName": "customPrice",
            "type": "CartItemCustomPrice",
            "format": ""
        },
        {
            "name": "vatAmount",
            "baseName": "vatAmount",
            "type": "CartMoney",
            "format": ""
        },
        {
            "name": "vatPercentage",
            "baseName": "vatPercentage",
            "type": "number",
            "format": "float"
        },
        {
            "name": "vatInaccurate",
            "baseName": "vatInaccurate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "vatCalculated",
            "baseName": "vatCalculated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "localizedName",
            "baseName": "localizedName",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "productCode",
            "baseName": "productCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "productSku",
            "baseName": "productSku",
            "type": "string",
            "format": ""
        },
        {
            "name": "imageGrn",
            "baseName": "imageGrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "variantOptions",
            "baseName": "variantOptions",
            "type": "string",
            "format": ""
        },
        {
            "name": "isVirtual",
            "baseName": "isVirtual",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "promotionGrns",
            "baseName": "promotionGrns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "string",
            "format": ""
        },
        {
            "name": "productData",
            "baseName": "productData",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CartCartItem.attributeTypeMap;
    }

    public constructor() {
    }
}

