/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartLocalizedText } from '../models/CartLocalizedText';
import { CartMoney } from '../models/CartMoney';
import { OptionImage } from '../models/OptionImage';
import { HttpFile } from '../http/http';

export class CartProductConfigurationStepOption {
    'id'?: string;
    'grn'?: string;
    'label'?: CartLocalizedText;
    'priceVariation'?: CartMoney;
    'weightVariation'?: number;
    'image'?: OptionImage;
    'hasQuantity'?: boolean;
    'quantity'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "grn",
            "baseName": "grn",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "CartLocalizedText",
            "format": ""
        },
        {
            "name": "priceVariation",
            "baseName": "priceVariation",
            "type": "CartMoney",
            "format": ""
        },
        {
            "name": "weightVariation",
            "baseName": "weightVariation",
            "type": "number",
            "format": "float"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "OptionImage",
            "format": ""
        },
        {
            "name": "hasQuantity",
            "baseName": "hasQuantity",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return CartProductConfigurationStepOption.attributeTypeMap;
    }

    public constructor() {
    }
}

