/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartLocalizedText } from '../models/CartLocalizedText';
import { CartProductConfigurationStepOption } from '../models/CartProductConfigurationStepOption';
import { HttpFile } from '../http/http';

export class CartProductConfigurationStep {
    'id'?: string;
    'grn'?: string;
    'label'?: CartLocalizedText;
    'description'?: CartLocalizedText;
    'options'?: Array<CartProductConfigurationStepOption>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "grn",
            "baseName": "grn",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "CartLocalizedText",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "CartLocalizedText",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<CartProductConfigurationStepOption>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CartProductConfigurationStep.attributeTypeMap;
    }

    public constructor() {
    }
}

