/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartProductConfigurationSelection } from '../models/CartProductConfigurationSelection';
import { HttpFile } from '../http/http';

export class CartAddProductsRequestItem {
    'productGrn'?: string;
    'quantity'?: number;
    'configurationSelections'?: Array<CartProductConfigurationSelection>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productGrn",
            "baseName": "productGrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "configurationSelections",
            "baseName": "configurationSelections",
            "type": "Array<CartProductConfigurationSelection>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CartAddProductsRequestItem.attributeTypeMap;
    }

    public constructor() {
    }
}

