/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartCartData } from '../models/CartCartData';
import { HttpFile } from '../http/http';

export class CartGetCartResponse {
    'cart'?: CartCartData;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cart",
            "baseName": "cart",
            "type": "CartCartData",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CartGetCartResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

