/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartProductConfigurationSelectionOption } from '../models/CartProductConfigurationSelectionOption';
import { HttpFile } from '../http/http';

export class CartProductConfigurationSelection {
    'stepGrn'?: string;
    'options'?: Array<CartProductConfigurationSelectionOption>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "stepGrn",
            "baseName": "stepGrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<CartProductConfigurationSelectionOption>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CartProductConfigurationSelection.attributeTypeMap;
    }

    public constructor() {
    }
}

