/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartSortOrder } from '../models/CartSortOrder';
import { SortSortField } from '../models/SortSortField';
import { HttpFile } from '../http/http';

export class ListCartsRequestSort {
    /**
    * evaluation_order is the order in which the sort will be applied. The lower the number, the earlier the sort will be applied.
    */
    'evaluationOrder'?: number;
    'field'?: SortSortField;
    'order'?: CartSortOrder;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "evaluationOrder",
            "baseName": "evaluationOrder",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "SortSortField",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "CartSortOrder",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListCartsRequestSort.attributeTypeMap;
    }

    public constructor() {
    }
}



