/**
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartCartStatus } from '../models/CartCartStatus';
import { CartCustomerData } from '../models/CartCustomerData';
import { HttpFile } from '../http/http';

export class UpdateCartRequestPayload {
    'cartStatus'?: CartCartStatus;
    'customerData'?: CartCustomerData;
    'locale'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cartStatus",
            "baseName": "cartStatus",
            "type": "CartCartStatus",
            "format": ""
        },
        {
            "name": "customerData",
            "baseName": "customerData",
            "type": "CartCustomerData",
            "format": ""
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateCartRequestPayload.attributeTypeMap;
    }

    public constructor() {
    }
}



